### ISSUE TITLE
Edit commits before pull request

### ISSUE THREAD

**Issue by JonasNorling** [jimeh/common-flow#11]
While it is "RECOMMENDED that you commit often locally", I think that the flow should allow for (or indeed encourage) developers to reformat this stream of commits into a comprehensible patch set before opening a pull request. This would add a "git rebase -i" step before creating the pull request, where commits can be squashed and reordered and commit messages touched up.

Also: although I don't see this spelled out, the diagram suggests that issues that come up in review get fixed by adding more commits. I would suggest allowing (and recommending) the original commits to be fixed and re-uploaded for review instead, as this produces a cleaner history and also makes several review passes manageable. This is the natural workflow with some tooling (e.g. Gerrit).

**Comment by jimeh** [comment]
Thanks for the feedback. I don't fully agree with cleaning up commit history as I often find it useful to see the steps that were taken to reach a certain solution. However a messy/random commit history is not very fun.

Hence I'm not overly hyped at the idea of specifically suggesting that you should rewrite history to the cleanest possible state, and rewrite the original changes after pull request feedback.

So instead, how about I change the spec simply to suggest that you should try to keep commit history reasonably clean and easy to follow, while mentioning that `git rebase -i` can be used if you find yourself unhappy with the history as is. Basically leaving it up to the user to decide if, when and how commit history should be cleaned up, instead of encouraging the user to always do it.

**Comment by JonasNorling** [comment]
Yes, that sounds good. It's good to mention that it _can_ be done.

I agree that it can be good to keep a record of lessons learned and paths taken or not taken when implementing the code. I just think it's better to write that up as prose in commit messages and code comments, because that's nicer to reviewers and the future me. However, I acknowledge that that doesn't actually happen as often as it should :-). Also, tooling is going to affect what process feels right, and I'm currently more used to Gerrit than to GitHub.
