### ISSUE TITLE
Mandatory rebasing is too strict a policy

### ISSUE THREAD

**Issue by phodge** [jimeh/common-flow#8]
We've just migrated across to git and enterprise GitHub in my workplace. While many of us would like to rebase everything all the time to keep a clean history, we've actually had to implement a BAN on rebasing for any branch which has become part of a GitHub Pull Request. The reason for this is simply that GitHub can't track which comments belonged to which commits if you rebase.

While I personally appreciate the value of rebasing, making it a mandatory part of common-flow makes it impossible for us to adopt this policy without modifications.

**Comment by jimeh** [comment]
Thanks for the feedback. This has been pointed out in a discussion on Reddit already, and I am planning to change the requirement to allow for either rebasing or merging depending on your needs.

Hopefully this should help you, and please speak up if there's anything else that you might have issues with, or would like added :)

**Comment by mbitsnbites** [comment]
I think that having rebase vs merge as an option could be confusing, so please make it very clear that the choice is made for each project/organization, *not* for each developer or each commit. It almost deserves a separate branching strategy name (similar to how there are different flavors of Creative Commons).

**Comment by jimeh** [comment]
@mbitsnbites Agreed, it needs to be made very clear at what level the choice needs to be made. I don't think it's worth spinning off a whole different flow though. Specially since there's already optional things in the spec. We can't create a different flow for every combination of features, instead I see it as here's a foundation, and here's various features you can use if you so choose.

**Comment by jimeh** [comment]
@phodge @mbitsnbites I believe PR #13 has resolved this issue. If you disagree, please let me know :)
